
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async changeBinding(id: string, binding: string) : Promise<Result<BindingResponse, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_binding", { id, binding }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async resetBinding(id: string) : Promise<Result<BindingResponse, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("reset_binding", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changePttSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_ptt_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeAudioFeedbackSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_audio_feedback_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeAudioFeedbackVolumeSetting(volume: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_audio_feedback_volume_setting", { volume }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeSoundThemeSetting(theme: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_sound_theme_setting", { theme }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeStartHiddenSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_start_hidden_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeAutostartSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_autostart_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeTranslateToEnglishSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_translate_to_english_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeSelectedLanguageSetting(language: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_selected_language_setting", { language }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeOpenrouterCustomModelSetting(model: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_openrouter_custom_model_setting", { model }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeOverlayPositionSetting(position: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_overlay_position_setting", { position }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeDebugModeSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_debug_mode_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeWordCorrectionThresholdSetting(threshold: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_word_correction_threshold_setting", { threshold }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeExtraRecordingBufferSetting(ms: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_extra_recording_buffer_setting", { ms }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeMeetingAutoSummarizeSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_meeting_auto_summarize_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeMeetingAutoDetectSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_meeting_auto_detect_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Meeting mode: pick the Gemini Live mode — `"off"`, `"translate"` or
 * `"transcribe"`. Rejects anything else rather than persisting a value the
 * backend would silently read as "off".
 */
async changeMeetingLiveModeSetting(mode: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_meeting_live_mode_setting", { mode }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Meeting mode: set the BCP-47 language live translation translates INTO.
 */
async changeMeetingLiveTranslateTargetSetting(language: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_meeting_live_translate_target_setting", { language }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Meeting mode: run the on-stop finalize pass through Gemini batch
 * transcription (speaker attribution) instead of local Whisper windows.
 * Meeting mode: turn speaker attribution on or off for the Gemini finalize pass.
 */
async changeMeetingGeminiDiarizeSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_meeting_gemini_diarize_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Meeting mode: cleaned-up ("smart") vs. verbatim Gemini transcription.
 */
async changeMeetingGeminiSmartSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_meeting_gemini_smart_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Meeting mode: show or hide the live subtitle strip.
 */
async changeMeetingSubtitlesSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_meeting_subtitles_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Meeting mode: choose which model transcribes meetings. An empty string
 * means "follow the dictation model", which is the default.
 * 
 * Rejects unknown ids so a typo cannot leave meetings pointing at a model that
 * does not exist — the live pass would then fail on every segment with nothing
 * on screen explaining why.
 */
async changeMeetingSelectedModelSetting(modelId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_meeting_selected_model_setting", { modelId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Store the Gemini API key used by every Gemini meeting path. An empty
 * string clears it.
 */
async changeGeminiApiKeySetting(apiKey: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_gemini_api_key_setting", { apiKey }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeMeetingAutoEndSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_meeting_auto_end_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeMeetingCalendarNamesSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_meeting_calendar_names_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Set (or clear, with an empty string) the folder completed meetings are
 * copied to as Markdown. Existing meetings are not back-filled.
 */
async changeMeetingExportDirSetting(dir: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_meeting_export_dir_setting", { dir }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeMeetingSilenceTimeoutSetting(secs: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_meeting_silence_timeout_setting", { secs }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeMeetingAutoEndGraceSetting(secs: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_meeting_auto_end_grace_setting", { secs }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changePasteMethodSetting(method: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_paste_method_setting", { method }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getAvailableTypingTools() : Promise<string[]> {
    return await TAURI_INVOKE("get_available_typing_tools");
},
async changeTypingToolSetting(tool: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_typing_tool_setting", { tool }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeExternalScriptPathSetting(path: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_external_script_path_setting", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeClipboardHandlingSetting(handling: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_clipboard_handling_setting", { handling }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeAutoSubmitSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_auto_submit_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeAutoSubmitKeySetting(key: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_auto_submit_key_setting", { key }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changePostProcessEnabledSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_post_process_enabled_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeExperimentalEnabledSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_experimental_enabled_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changePostProcessBaseUrlSetting(providerId: string, baseUrl: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_post_process_base_url_setting", { providerId, baseUrl }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changePostProcessApiKeySetting(providerId: string, apiKey: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_post_process_api_key_setting", { providerId, apiKey }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changePostProcessModelSetting(providerId: string, model: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_post_process_model_setting", { providerId, model }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setPostProcessProvider(providerId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_post_process_provider", { providerId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async fetchPostProcessModels(providerId: string) : Promise<Result<string[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("fetch_post_process_models", { providerId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async addPostProcessPrompt(name: string, prompt: string) : Promise<Result<LLMPrompt, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_post_process_prompt", { name, prompt }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updatePostProcessPrompt(id: string, name: string, prompt: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_post_process_prompt", { id, name, prompt }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deletePostProcessPrompt(id: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_post_process_prompt", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setPostProcessSelectedPrompt(id: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_post_process_selected_prompt", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateCustomWords(words: string[]) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_custom_words", { words }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Temporarily unregister a binding while the user is editing it in the UI.
 * This avoids firing the action while keys are being recorded.
 */
async suspendBinding(id: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("suspend_binding", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Re-register the binding after the user has finished editing.
 */
async resumeBinding(id: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("resume_binding", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeMuteWhileRecordingSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_mute_while_recording_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeAppendTrailingSpaceSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_append_trailing_space_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeLazyStreamCloseSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_lazy_stream_close_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeAppLanguageSetting(language: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_app_language_setting", { language }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeUpdateChecksSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_update_checks_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Change the keyboard implementation with runtime switching.
 * This will unregister all shortcuts from the old implementation,
 * validate shortcuts for the new implementation (resetting invalid ones to defaults),
 * and register them with the new implementation.
 */
async changeKeyboardImplementationSetting(implementation: string) : Promise<Result<ImplementationChangeResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_keyboard_implementation_setting", { implementation }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get the current keyboard implementation
 */
async getKeyboardImplementation() : Promise<string> {
    return await TAURI_INVOKE("get_keyboard_implementation");
},
async changeShowTrayIconSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_show_tray_icon_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeWhisperAcceleratorSetting(accelerator: WhisperAcceleratorSetting) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_whisper_accelerator_setting", { accelerator }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeOrtAcceleratorSetting(accelerator: OrtAcceleratorSetting) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_ort_accelerator_setting", { accelerator }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Return which ORT accelerators are compiled into this build.
 */
async getAvailableAccelerators() : Promise<AvailableAccelerators> {
    return await TAURI_INVOKE("get_available_accelerators");
},
/**
 * Start key recording mode
 */
async startHandyKeysRecording(bindingId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("start_handy_keys_recording", { bindingId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Stop key recording mode
 */
async stopHandyKeysRecording() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("stop_handy_keys_recording") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async triggerUpdateCheck() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("trigger_update_check") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async showMainWindowCommand() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("show_main_window_command") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cancelOperation() : Promise<void> {
    await TAURI_INVOKE("cancel_operation");
},
async getAppDirPath() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_app_dir_path") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getAppSettings() : Promise<Result<AppSettings, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_app_settings") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getDefaultSettings() : Promise<Result<AppSettings, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_default_settings") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getLogDirPath() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_log_dir_path") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setLogLevel(level: LogLevel) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_log_level", { level }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async openRecordingsFolder() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_recordings_folder") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async openLogDir() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_log_dir") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async openAppDataDir() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_app_data_dir") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Check if Apple Intelligence is available on this device.
 * Called by the frontend when the user selects Apple Intelligence provider.
 */
async checkAppleIntelligenceAvailable() : Promise<boolean> {
    return await TAURI_INVOKE("check_apple_intelligence_available");
},
/**
 * Try to initialize Enigo (keyboard/mouse simulation).
 * On macOS, this will return an error if accessibility permissions are not granted.
 */
async initializeEnigo() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("initialize_enigo") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Initialize keyboard shortcuts.
 * On macOS, this should be called after accessibility permissions are granted.
 * This is idempotent - calling it multiple times is safe.
 */
async initializeShortcuts() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("initialize_shortcuts") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getAvailableModels() : Promise<Result<ModelInfo[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_available_models") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getModelInfo(modelId: string) : Promise<Result<ModelInfo | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_model_info", { modelId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async downloadModel(modelId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("download_model", { modelId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteModel(modelId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_model", { modelId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cancelDownload(modelId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cancel_download", { modelId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setActiveModel(modelId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_active_model", { modelId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getCurrentModel() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_current_model") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getTranscriptionModelStatus() : Promise<Result<string | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_transcription_model_status") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async isModelLoading() : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("is_model_loading") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async hasAnyModelsAvailable() : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("has_any_models_available") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async hasAnyModelsOrDownloads() : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("has_any_models_or_downloads") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateMicrophoneMode(alwaysOn: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_microphone_mode", { alwaysOn }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getMicrophoneMode() : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_microphone_mode") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getWindowsMicrophonePermissionStatus() : Promise<WindowsMicrophonePermissionStatus> {
    return await TAURI_INVOKE("get_windows_microphone_permission_status");
},
async openMicrophonePrivacySettings() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_microphone_privacy_settings") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getAvailableMicrophones() : Promise<Result<AudioDevice[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_available_microphones") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setSelectedMicrophone(deviceName: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_selected_microphone", { deviceName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getSelectedMicrophone() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_selected_microphone") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getAvailableOutputDevices() : Promise<Result<AudioDevice[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_available_output_devices") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setSelectedOutputDevice(deviceName: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_selected_output_device", { deviceName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getSelectedOutputDevice() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_selected_output_device") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async playTestSound(soundType: string) : Promise<void> {
    await TAURI_INVOKE("play_test_sound", { soundType });
},
async checkCustomSounds() : Promise<CustomSounds> {
    return await TAURI_INVOKE("check_custom_sounds");
},
async setClamshellMicrophone(deviceName: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_clamshell_microphone", { deviceName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getClamshellMicrophone() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_clamshell_microphone") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async isRecording() : Promise<boolean> {
    return await TAURI_INVOKE("is_recording");
},
/**
 * Meeting mode (Step 1) test: capture `seconds` of system audio via the
 * CoreAudio tap and write it to a 32-bit float WAV in the temp dir. Returns the
 * output path.
 * 
 * On macOS this triggers the Audio-Capture permission dialog on first run
 * (NSAudioCaptureUsageDescription, macOS 14.4+). Must run inside the bundled
 * app for the permission to be granted. This command is isolated from the
 * existing dictation flow.
 */
async captureSystemAudioTest(seconds: number) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("capture_system_audio_test", { seconds }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Meeting mode (Step 2) test: capture `seconds` of BOTH the microphone and
 * system audio, resample each to 16 kHz mono, mix them with clipping
 * prevention, and write the mixed result to a 16 kHz mono f32 WAV in the temp
 * dir. Returns the output path.
 * 
 * This is the transcription-ready target rate (`WHISPER_SAMPLE_RATE = 16000`),
 * so the output is directly usable by `TranscriptionManager::transcribe`.
 * 
 * Design: resample-then-mix. The mic is captured on a dedicated cpal input
 * stream (independent of the dictation `AudioRecordingManager` singleton),
 * resampled to 16 kHz via `FrameResampler`, and forwarded over a channel. The
 * system audio comes from Step 1's `SystemAudioStream` (~48 kHz), resampled to
 * 16 kHz. Both feed a `MeetingMixer` that mixes in 100 ms windows.
 * 
 * On macOS this triggers BOTH the Audio-Capture (system) and Microphone
 * permission dialogs. Must run inside the bundled app. Isolated from the
 * existing dictation flow.
 */
async captureMixedAudioTest(seconds: number) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("capture_mixed_audio_test", { seconds }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Start a continuous meeting session: ensure the transcription model is
 * loaded, then begin capturing mixed mic + system audio, segmenting it with
 * VAD, and transcribing each segment.
 * 
 * macOS-only (CoreAudio tap). Returns an "unsupported" error on other
 * platforms.
 */
async startMeeting() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("start_meeting") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Stop the meeting session. Resolves once the meeting is fully saved, with
 * the id of the row that was persisted (`None` when the empty session was
 * discarded) and the final transcript. Errors when a stop is already in
 * progress.
 */
async stopMeeting() : Promise<Result<StopMeetingResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("stop_meeting") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Return the transcript accumulated so far (for polling during a session).
 */
async getMeetingTranscript() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_meeting_transcript") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Return the meeting slot status: `"idle"`, `"running"` or `"finalizing"`.
 */
async getMeetingStatus() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_meeting_status") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * State, live row id and start time of the meeting slot — the same payload
 * as the `meeting-session-changed` event.
 */
async getMeetingSession() : Promise<Result<MeetingSessionInfo, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_meeting_session") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Return the live session's start time as epoch milliseconds, or `null`
 * when no session is running. The UI uses it to render a truthful elapsed
 * timer when it attaches to a session that was started elsewhere (tray, global
 * shortcut, or the meeting auto-detect prompt).
 */
async getMeetingStartedAt() : Promise<Result<number | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_meeting_started_at") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Summarize the most recent meeting's transcript into meeting notes using the
 * SAME LLM provider/model/api-key the user configured for dictation
 * post-processing. The summary is saved onto that meeting's row (and
 * announced on `meeting-summary-update`) when it has been saved.
 */
async summarizeMeeting() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("summarize_meeting") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Like `summarize_meeting`, but with an optional template selector + custom
 * prompt override. `template` is matched first against a configured
 * `meeting_summary_templates` id; if no template matches it is treated as a
 * raw custom prompt. `None`/empty → the default prompt.
 */
async summarizeMeetingWith(template: string | null) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("summarize_meeting_with", { template }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Regenerate the summary for an ALREADY-PERSISTED meeting `id` (e.g. the user
 * picked a different template). Reads the stored transcript + user notes,
 * runs the summary, persists it onto that row, and returns it.
 */
async regenerateMeetingSummary(id: number, template: string | null) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("regenerate_meeting_summary", { id, template }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * List persisted meetings, newest-first (lightweight rows). When `query` is a
 * non-empty string, filters by a case-insensitive substring match against the
 * title, transcript, or summary. `None`/empty → all meetings (legacy behavior).
 */
async listMeetings(query: string | null) : Promise<Result<MeetingListItem[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_meetings", { query }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Fetch a single full meeting record (transcript + segments + summary).
 */
async getMeeting(id: number) : Promise<Result<MeetingRecord, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_meeting", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Return the absolute filesystem path to a meeting's saved mixed-audio WAV,
 * for the frontend to play back. The frontend should pass this path to
 * Tauri's `convertFileSrc()` and use the result as an `<audio>` `src`; the
 * app's asset protocol is enabled with a broad scope so the converted URL is
 * directly loadable. Errors if the meeting has no saved audio.
 */
async getMeetingAudioPath(id: number) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_meeting_audio_path", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Delete a persisted meeting by id, with everything it owns on disk (capture
 * buffers, playback audio, exported note). Errors for the meeting that is
 * in progress (running or still being saved).
 */
async deleteMeeting(id: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_meeting", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Discard an interrupted meeting: delete the row AND the files only it
 * referenced (its raw capture buffers, which exist purely so the row can be
 * re-finalized, plus any playback audio). Errors for the meeting that is in
 * progress — it is in `recording` status too, but it is not interrupted.
 */
async discardInterruptedMeeting(id: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("discard_interrupted_meeting", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getTranscriptionLocation() : Promise<Result<TranscriptionLocation, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_transcription_location") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Manually rename a meeting (Phase 2 item 2). Overwrites the `title` column.
 */
async updateMeetingTitle(id: number, title: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_meeting_title", { id, title }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Save the user's own editable notes for a meeting. Distinct from the AI
 * `summary`; stored in the `notes` column. Works on the in-progress
 * (`recording`) row too, so notes can be autosaved live — finalize never
 * writes the notes column, so nothing typed here is overwritten.
 */
async updateMeetingNotes(id: number, notes: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_meeting_notes", { id, notes }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Export a meeting as a clean Markdown document (Phase 2 item 6): title,
 * date/time, duration, labeled transcript, user notes, and AI summary. The
 * frontend handles the file-save dialog (Phase 4); this returns the string.
 */
async exportMeetingMarkdown(id: number) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("export_meeting_markdown", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * List meetings interrupted by a crash/OS-kill (still in `recording` status),
 * newest-first, excluding the meeting that is running or being saved right
 * now. Each item reports whether its capture buffers still exist so the UI
 * can offer a high-quality re-finalize vs. salvaging the partial text.
 */
async listInterruptedMeetings() : Promise<Result<InterruptedMeeting[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_interrupted_meetings") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Recover an interrupted meeting (Phase 2 item 1). If the per-source temp audio
 * buffers still exist, re-runs the finalize pass for a high-quality labeled
 * transcript and saves the mixed playback WAV; otherwise keeps the partial
 * transcript that was incrementally saved. Either way the row is flipped to
 * `completed` (so it isn't offered for recovery again) and the temp files are
 * cleaned up. Returns the recovered full transcript.
 */
async recoverMeeting(id: number) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("recover_meeting", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Import a recording made elsewhere (a phone voice memo, a conference
 * recording) as a meeting: decode, transcribe with the meeting model, title
 * and summarize, save to History. Returns the new meeting id. Progress arrives
 * as `"meeting-import-progress"`, the outcome also as
 * `"meeting-import-finished"`.
 */
async importMeetingRecording(path: string) : Promise<Result<number, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("import_meeting_recording", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Cancel the running import at its next checkpoint.
 */
async cancelMeetingImport() : Promise<void> {
    await TAURI_INVOKE("cancel_meeting_import");
},
/**
 * Transcribe a saved meeting again from its stored audio, replacing its
 * transcript (and summary, when it had one). For meetings that came back
 * empty or garbled. Shares the import's progress/finished events and cancel.
 */
async retranscribeMeeting(id: number) : Promise<Result<number, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("retranscribe_meeting", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Where the running import is, or `None` when nothing is importing.
 */
async getMeetingImportProgress() : Promise<MeetingImportProgress | null> {
    return await TAURI_INVOKE("get_meeting_import_progress");
},
/**
 * File extensions the import accepts, for the file picker and drag-and-drop.
 */
async getSupportedImportExtensions() : Promise<string[]> {
    return await TAURI_INVOKE("get_supported_import_extensions");
},
/**
 * User accepted the auto-detection "start transcription?" prompt: hides the
 * prompt window and starts a meeting session (same shared path as the UI
 * button / tray / shortcut).
 */
async acceptMeetingPrompt() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("accept_meeting_prompt") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * User dismissed the auto-detection "start transcription?" prompt: hides the
 * prompt window and snoozes detection until the current meeting-app signal
 * clears (so the same meeting doesn't re-prompt).
 */
async dismissMeetingPrompt() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("dismiss_meeting_prompt") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * User answered the "end meeting?" prompt. `continue_meeting` true keeps the
 * session running (and resets the silence timer); false stops it (finalize
 * runs on a blocking thread inside the helper).
 */
async respondMeetingAutoEnd(continueMeeting: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("respond_meeting_auto_end", { continueMeeting }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Snapshot of the meeting auto-detection state (whether a meeting app is
 * currently using the microphone, and which one) for the settings UI.
 */
async getMeetingDetectionStatus() : Promise<Result<MeetingDetectionStatus, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_meeting_detection_status") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Authorization status of macOS calendar access for meeting naming:
 * `"authorized"` | `"denied"` | `"notDetermined"` | `"unavailable"`.
 */
async getCalendarAccessStatus() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_calendar_access_status") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Request macOS calendar access for meeting naming, showing the system prompt
 * on first call. Resolves `true` when full access is granted. Runs on a
 * blocking thread — the system prompt can stay open for a while.
 */
async requestCalendarAccess() : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("request_calendar_access") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setModelUnloadTimeout(timeout: ModelUnloadTimeout) : Promise<void> {
    await TAURI_INVOKE("set_model_unload_timeout", { timeout });
},
async getModelLoadStatus() : Promise<Result<ModelLoadStatus, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_model_load_status") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async unloadModelManually() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("unload_model_manually") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getHistoryEntries(cursor: number | null, limit: number | null) : Promise<Result<PaginatedHistory, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_history_entries", { cursor, limit }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async toggleHistoryEntrySaved(id: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("toggle_history_entry_saved", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getAudioFilePath(fileName: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_audio_file_path", { fileName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteHistoryEntry(id: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_history_entry", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async retryHistoryEntryTranscription(id: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("retry_history_entry_transcription", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateHistoryLimit(limit: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_history_limit", { limit }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateRecordingRetentionPeriod(period: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_recording_retention_period", { period }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Checks if the Mac is a laptop by detecting battery presence
 * 
 * This uses pmset to check for battery information.
 * Returns true if a battery is detected (laptop), false otherwise (desktop)
 */
async isLaptop() : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("is_laptop") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/


export const events = __makeEvents__<{
historyUpdatePayload: HistoryUpdatePayload
}>({
historyUpdatePayload: "history-update-payload"
})

/** user-defined constants **/



/** user-defined types **/

export type AppSettings = { bindings: Partial<{ [key in string]: ShortcutBinding }>; push_to_talk: boolean; audio_feedback: boolean; audio_feedback_volume?: number; sound_theme?: SoundTheme; start_hidden?: boolean; autostart_enabled?: boolean; update_checks_enabled?: boolean; selected_model?: string; always_on_microphone?: boolean; selected_microphone?: string | null; clamshell_microphone?: string | null; selected_output_device?: string | null; translate_to_english?: boolean; selected_language?: string; overlay_position?: OverlayPosition; debug_mode?: boolean; log_level?: LogLevel; custom_words?: string[]; model_unload_timeout?: ModelUnloadTimeout; word_correction_threshold?: number; history_limit?: number; recording_retention_period?: RecordingRetentionPeriod; paste_method?: PasteMethod; clipboard_handling?: ClipboardHandling; auto_submit?: boolean; auto_submit_key?: AutoSubmitKey; post_process_enabled?: boolean; post_process_provider_id?: string; post_process_providers?: PostProcessProvider[]; post_process_api_keys?: Partial<{ [key in string]: string }>; post_process_models?: Partial<{ [key in string]: string }>; post_process_prompts?: LLMPrompt[]; post_process_selected_prompt_id?: string | null; 
/**
 * Custom OpenRouter model slug used by the "Custom OpenRouter model" cloud
 * transcription entry (e.g. `openai/gpt-4o-mini-transcribe`). Empty unless
 * the user enters one in Settings → Models.
 */
openrouter_custom_model?: string; mute_while_recording?: boolean; append_trailing_space?: boolean; app_language?: string; experimental_enabled?: boolean; lazy_stream_close?: boolean; keyboard_implementation?: KeyboardImplementation; show_tray_icon?: boolean; paste_delay_ms?: number; typing_tool?: TypingTool; external_script_path: string | null; custom_filler_words?: string[] | null; whisper_accelerator?: WhisperAcceleratorSetting; ort_accelerator?: OrtAcceleratorSetting; extra_recording_buffer_ms?: number; 
/**
 * Meeting mode: automatically summarize the meeting transcript on stop
 * (using the active post-process provider). Additive; defaults to false.
 */
meeting_auto_summarize?: boolean; 
/**
 * Meeting mode: which model transcribes meetings, independent of the model
 * dictation uses.
 * 
 * Empty (the default) means "whatever dictation uses", which is both the
 * old behaviour and a sensible default — it keeps following
 * [`Self::selected_model`] when the user changes that. Set it to run
 * meetings on something else: an accurate cloud model for meetings while
 * push-to-talk dictation stays local and free.
 * 
 * Read through [`Self::meeting_model_id`], never directly.
 */
meeting_selected_model?: string; 
/**
 * Meeting mode: the model used for the high-quality FINAL (on-stop)
 * re-transcription pass. Swapped in for finalize only, then the meeting
 * model is restored. Defaults to "turbo" (large-v3-turbo). The LIVE
 * preview path uses [`Self::meeting_model_id`].
 */
meeting_final_model?: string; 
/**
 * Meeting mode: language forced for meeting transcription windows. Fixes
 * per-window language flapping that auto-detect causes. Defaults to "tr"
 * (Turkish). Set to "auto" to restore per-window auto-detect. Only affects
 * the meeting path; dictation keeps using `selected_language`.
 */
meeting_language?: string; 
/**
 * Meeting mode: preset summary prompt templates the user can choose from
 * when summarizing a meeting. Each produces structured markdown. Additive;
 * defaults to a built-in set (General / Standup / 1:1 / Decisions & Action
 * Items / Q&A). The picker UI is Phase 4; the backend exposes them now.
 */
meeting_summary_templates?: MeetingSummaryTemplate[]; 
/**
 * Meeting mode: automatically detect when a meeting app (Zoom, Teams, a
 * browser running Meet, …) starts using the microphone and show a prompt
 * offering to start a transcription session. macOS only. Opt-in.
 */
meeting_auto_detect?: boolean; 
/**
 * Meeting mode: while a session is running, offer to end it after
 * `meeting_silence_timeout_secs` of continuous silence (or when the
 * detected meeting app releases the microphone), and end it automatically
 * if the prompt goes unanswered for `meeting_auto_end_grace_secs`.
 */
meeting_auto_end?: boolean; 
/**
 * Seconds of continuous silence before the "end meeting?" prompt appears.
 */
meeting_silence_timeout_secs?: number; 
/**
 * Meeting mode: name new sessions after the calendar event in progress at
 * start time (macOS EventKit). Opt-in: enabling prompts for the Calendars
 * permission. Window-title naming and the LLM auto-title stay available
 * regardless.
 */
meeting_calendar_names?: boolean; 
/**
 * Meeting mode: folder every completed meeting is also written to as a
 * Markdown file (an Obsidian vault, a notes repo). Empty = off. The file is
 * rewritten when the meeting's title, summary or notes change.
 */
meeting_export_dir?: string; 
/**
 * Seconds the "end meeting?" prompt waits for a response before the
 * session is ended automatically.
 */
meeting_auto_end_grace_secs?: number; 
/**
 * Meeting mode: stream the meeting audio to the Gemini Live API instead of
 * waiting for the on-stop finalize pass. One of `"off"`, `"translate"`
 * (speech-to-speech translation, reports original + translation) or
 * `"transcribe"` (transcription only, several times cheaper). Opt-in,
 * needs `gemini_api_key`. macOS only (it rides the meeting capture loop).
 */
meeting_live_mode?: string; 
/**
 * BCP-47 code live translation translates INTO (e.g. "en", "tr", "de").
 */
meeting_live_translate_target?: string; 
/**
 * Live API model id used for live translation. Overridable so a newer
 * preview can be selected without a rebuild.
 */
meeting_live_translate_model?: string; 
/**
 * Live API model id used for live transcription (no translation).
 */
meeting_live_transcribe_model?: string; 
/**
 * DEPRECATED, kept only so [`migrate_gemini_finalize_to_meeting_model`]
 * can read it off existing installs.
 * 
 * This used to be a toggle: "run the on-stop finalize through Gemini
 * instead of the local Whisper windows". Choosing Gemini as the meeting
 * model now says the same thing in one place, and having both meant two
 * Gemini paths of different quality selected by a hidden boolean. Nothing
 * reads this field any more; the migration clears it.
 */
meeting_gemini_finalize?: boolean; 
/**
 * Batch transcription model id for the Gemini finalize pass.
 */
meeting_gemini_finalize_model?: string; 
/**
 * Ask the batch finalize pass to attribute speech to distinct speakers.
 * Automatically skipped for audio past the API's 30-minute diarization
 * limit.
 */
meeting_gemini_diarize?: boolean; 
/**
 * Ask Gemini to clean disfluencies and format the transcript ("smart"
 * mode) rather than transcribe verbatim. Applies to both the batch
 * finalize pass and live transcription.
 */
meeting_gemini_smart?: boolean; 
/**
 * Show a click-through subtitle strip near the bottom of the screen while
 * a Gemini Live stream is running. Defaults ON because it only ever
 * appears once a live mode is already explicitly enabled — the text is the
 * thing that mode was turned on to produce, and the app window is not
 * where anyone is looking during a call.
 */
meeting_subtitles?: boolean; 
/**
 * Domain terms, names and product names Gemini should prefer, one per line
 * (commas also accepted). Used by both Gemini transcription paths.
 * DEPRECATED, kept only so [`migrate_meeting_vocabulary_into_custom_words`]
 * can read it off existing installs.
 * 
 * Meeting transcription used to keep its own term list while dictation had
 * [`Self::custom_words`], so the same name had to be typed twice — and it
 * was never obvious which list a term belonged in. Both now read
 * `custom_words`; the migration folds this one into it.
 */
meeting_custom_vocabulary?: string; 
/**
 * API key for Google's Gemini API, used by every Gemini meeting path.
 * Separate from `post_process_api_keys` because that map is keyed by
 * post-processing provider, and this is not one.
 */
gemini_api_key?: string }
export type AudioDevice = { index: string; name: string; is_default: boolean }
export type AutoSubmitKey = "enter" | "ctrl_enter" | "cmd_enter"
export type AvailableAccelerators = { whisper: string[]; ort: string[] }
export type BindingResponse = { success: boolean; binding: ShortcutBinding | null; error: string | null }
export type ClipboardHandling = "dont_modify" | "copy_to_clipboard"
export type CustomSounds = { start: boolean; stop: boolean }
export type EngineType = "Whisper" | "Parakeet" | "Moonshine" | "MoonshineStreaming" | "SenseVoice" | "GigaAM" | "Canary" | 
/**
 * Cloud transcription via OpenRouter using an audio-capable **chat** model
 * (e.g. `google/gemini-2.5-flash-lite`) and the chat-completions endpoint.
 * Not downloaded: `url`/`sha256` are `None`, `is_downloaded` is always
 * `true`, and `filename` carries the OpenRouter model slug instead of a
 * path. The OpenRouter API key is reused from the post-processing settings.
 */
"OpenRouter" | 
/**
 * Cloud transcription via OpenRouter using a dedicated **ASR** model (e.g.
 * `openai/whisper-1`, `openai/gpt-4o-transcribe`) and the
 * `/audio/transcriptions` endpoint — verbatim speech-to-text. Same
 * not-downloaded/`filename`-as-slug conventions as [`EngineType::OpenRouter`].
 */
"OpenRouterAsr" | 
/**
 * Cloud transcription straight from Google's Gemini API (not through
 * OpenRouter), using the same batch endpoint the meeting finalize pass
 * uses. Authenticated with `gemini_api_key` rather than the OpenRouter
 * key; `filename` carries the bare Gemini model id.
 * 
 * This is the only cloud engine that can attribute speakers and stream
 * live, which is why meetings can drive it beyond plain transcription.
 */
"Gemini" | 
/**
 * Streaming transcription over Gemini's Live API (WebSocket), fed while
 * the user is still speaking. Same key and slug-in-filename conventions as
 * [`EngineType::Gemini`], but it never goes through `transcribe()`: the
 * text already exists when the recording stops.
 */
"GeminiLive"
export type HistoryEntry = { id: number; file_name: string; timestamp: number; saved: boolean; title: string; transcription_text: string; post_processed_text: string | null; post_process_prompt: string | null; post_process_requested: boolean }
export type HistoryUpdatePayload = { action: "added"; entry: HistoryEntry } | { action: "updated"; entry: HistoryEntry } | { action: "deleted"; id: number } | { action: "toggled"; id: number }
/**
 * Result of changing keyboard implementation
 */
export type ImplementationChangeResult = { success: boolean; 
/**
 * List of binding IDs that were reset to defaults due to incompatibility
 */
reset_bindings: string[] }
/**
 * An interrupted meeting (status still `"recording"`) detected at startup, with
 * the info a recovery pass needs.
 */
export type InterruptedMeeting = { id: number; started_at: number; title: string; 
/**
 * Whatever partial transcript was incrementally saved before the crash.
 */
transcript: string; 
/**
 * True if the per-source temp audio buffers still exist on disk (so a
 * re-finalize can recover a high-quality transcript). False → only the
 * partial transcript can be salvaged.
 */
has_buffers: boolean }
export type KeyboardImplementation = "tauri" | "handy_keys"
export type LLMPrompt = { id: string; name: string; prompt: string }
export type LogLevel = "trace" | "debug" | "info" | "warn" | "error"
/**
 * Detection status snapshot for the frontend (settings UI / debugging).
 */
export type MeetingDetectionStatus = { 
/**
 * True when a meeting app is currently using the microphone.
 */
detected: boolean; 
/**
 * Human-readable name of the detected app, when `detected`.
 */
app_name: string | null }
/**
 * Event payload emitted on `"meeting-import-progress"` while a recording file
 * is imported. `progress` is 0..1 within the current stage, `None` when the
 * stage cannot measure itself (a single cloud request).
 */
export type MeetingImportProgress = { file_name: string; stage: MeetingImportStage; progress: number | null }
/**
 * Which step of an import is running, for `"meeting-import-progress"`.
 */
export type MeetingImportStage = "decoding" | "transcribing" | "summarizing"
/**
 * Lightweight row for the meetings list view (newest-first).
 */
export type MeetingListItem = { id: number; started_at: number; ended_at: number; duration_ms: number; title: string; has_summary: boolean; 
/**
 * Short preview of the transcript (first ~200 chars).
 */
transcript_preview: string; 
/**
 * Lifecycle status: `"recording"` (interrupted/in-progress) or
 * `"completed"`. The list view can surface a "needs recovery" badge.
 */
status: string }
/**
 * Full meeting record returned by `get_meeting`.
 */
export type MeetingRecord = { id: number; started_at: number; ended_at: number; duration_ms: number; title: string; transcript: string; segments: TranscriptSegment[]; summary: string | null; created_at: number; 
/**
 * Absolute path to the persisted mixed 16 kHz mono WAV, if saved.
 */
audio_path: string | null; 
/**
 * User's own editable notes, distinct from the AI `summary`.
 */
notes: string | null; 
/**
 * Lifecycle status: `"recording"` or `"completed"`.
 */
status: string; 
/**
 * Tokens the Gemini paths reported for this meeting. `None` for meetings
 * that used no cloud model, or that predate usage tracking — which is why
 * the UI must say "no data" rather than "$0.00".
 */
usage: MeetingUsage | null }
/**
 * Snapshot of the meeting slot for the UI (`get_meeting_session` and the
 * `meeting-session-changed` event).
 */
export type MeetingSessionInfo = { 
/**
 * `"idle"` | `"running"` | `"finalizing"`.
 */
state: string; 
/**
 * Row id of the live meeting (status `recording` until it completes).
 * `None` when idle, and briefly after start until the capture sources are
 * up and the row is inserted — a second `meeting-session-changed` event
 * follows the moment it is known.
 */
meeting_id: number | null; 
/**
 * Absolute epoch-ms start of the live meeting; `None` when idle.
 */
started_at_ms: number | null }
/**
 * A preset summary prompt template for meeting mode. `id` is a stable key the
 * frontend passes to `summarize_meeting_with`; `name` is the display label;
 * `prompt` is the system instruction sent to the LLM (it should instruct the
 * model to produce structured markdown and to answer in the transcript's
 * language).
 */
export type MeetingSummaryTemplate = { id: string; name: string; prompt: string }
/**
 * Everything a meeting spent, one entry per model involved.
 */
export type MeetingUsage = { entries: ModelUsage[] }
export type ModelInfo = { id: string; name: string; description: string; filename: string; url: string | null; sha256: string | null; size_mb: number; is_downloaded: boolean; is_downloading: boolean; partial_size: number; is_directory: boolean; engine_type: EngineType; accuracy_score: number; speed_score: number; supports_translation: boolean; is_recommended: boolean; supported_languages: string[]; supports_language_selection: boolean; is_custom: boolean }
export type ModelLoadStatus = { is_loaded: boolean; current_model: string | null }
export type ModelUnloadTimeout = "never" | "immediately" | "min_2" | "min_5" | "min_10" | "min_15" | "hour_1" | "sec_15"
/**
 * Tokens consumed by one model, split by direction.
 * 
 * The modality split is kept even though current pricing does not vary by it
 * within a single model: it costs nothing to record, and it is the difference
 * between "we can explain this number" and "trust us" when a translate session
 * (audio out) and a transcribe session (text out) sit side by side.
 */
export type ModelUsage = { 
/**
 * Bare model id the work was spent on.
 */
model: string; 
/**
 * Tokens the model consumed, when it reported them.
 */
input_tokens: number; 
/**
 * Tokens the model produced, when it reported them.
 */
output_tokens: number; 
/**
 * Seconds of audio streamed to this model.
 * 
 * Measured on our side, and for the Live API it is the ONLY basis
 * available: `gemini-3.5-transcribe-live` sends no `usageMetadata` at all
 * — verified by enumerating every distinct message shape across whole
 * meetings — so a token-only design silently reported nothing.
 */
audio_seconds?: number }
export type OrtAcceleratorSetting = "auto" | "cpu" | "cuda" | "directml" | "rocm"
export type OverlayPosition = "none" | "top" | "bottom"
export type PaginatedHistory = { entries: HistoryEntry[]; has_more: boolean }
export type PasteMethod = "ctrl_v" | "direct" | "none" | "shift_insert" | "ctrl_shift_v" | "external_script"
export type PermissionAccess = "allowed" | "denied" | "unknown"
export type PostProcessProvider = { id: string; label: string; base_url: string; allow_base_url_edit?: boolean; models_endpoint?: string | null; supports_structured_output?: boolean }
export type RecordingRetentionPeriod = "never" | "preserve_limit" | "days_3" | "weeks_2" | "months_3"
export type ShortcutBinding = { id: string; name: string; description: string; default_binding: string; current_binding: string }
export type SoundTheme = "marimba" | "pop" | "custom"
/**
 * What `stop_meeting` returns.
 */
export type StopMeetingResult = { 
/**
 * Row id of the meeting that was just saved; `None` when the session was
 * empty and discarded (or kept only for recovery, still `recording`).
 */
meeting_id: number | null; 
/**
 * Final transcript text.
 */
transcript: string }
/**
 * A single transcribed speech segment with its (relative) start timestamp.
 */
export type TranscriptSegment = { 
/**
 * Cleaned transcript text for this segment.
 */
text: string; 
/**
 * Milliseconds since the meeting session started.
 */
timestamp_ms: number; 
/**
 * Which captured source produced this segment (mic = "you",
 * system = "others").
 */
source?: TranscriptSource; 
/**
 * Translation of `text`, when the segment came from the Gemini Live
 * translation path. `None` for the normal transcription paths and for
 * records saved before live translation existed.
 */
translation?: string | null; 
/**
 * Which speaker said this, when the transcript came from a path that can
 * tell participants apart (the Gemini batch finalize pass with diarization
 * on). Holds a display label like `"Speaker 1"`, already resolved from the
 * API's raw `spk_1`. `None` everywhere else — `source` remains the only
 * attribution the local paths can offer.
 */
speaker?: string | null }
/**
 * Which captured source a transcript segment came from.
 * 
 * Serializes as `"you"` (microphone / the local speaker) and `"others"`
 * (system audio / remote participants) so the frontend can label segments
 * directly without an extra mapping step.
 */
export type TranscriptSource = "you" | "others"
/**
 * Where a meeting's transcription would actually run, for the trust
 * indicator.
 * 
 * The UI showed an unconditional "100% on-device" badge, which stopped being
 * true the moment a cloud transcription model or any Gemini path could be
 * selected. A privacy claim that is right most of the time is worse than no
 * claim: it is exactly the situation where the user stops checking.
 */
export type TranscriptionLocation = { 
/**
 * Names of the cloud services audio would be sent to. Empty means the
 * meeting really is fully on-device.
 */
cloud_providers: string[] }
export type TypingTool = "auto" | "wtype" | "kwtype" | "dotool" | "ydotool" | "xdotool"
export type WhisperAcceleratorSetting = "auto" | "cpu" | "gpu"
export type WindowsMicrophonePermissionStatus = { supported: boolean; overall_access: PermissionAccess; device_access: PermissionAccess; app_access: PermissionAccess; desktop_app_access: PermissionAccess }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
